### ISSUE TITLE
Return the "string" representation of tokens or their text offsets

### ISSUE THREAD

**Issue by Egyptmaster** [georg-jung/FastBertTokenizer#38]
Hi,

I came with the issue that I need to get the "string" representations of the tokens returned by the Encode method. Alternative can be to get the offsets. Is there a chance to get the offsets/string of a input_id ?

**Comment by Egyptmaster** [comment]
Well, currently I am using the BERT tokenization only as a first step in a processing pipeline. The token_ids returned by your tokenizer are used for NER using a corresponding model from hugging-face (which I converted to ONNX model to make it running in dotnet). The ONNX model returns predictions as "scores" for each possible trained labels (e.g. I-LOC) for each of the input tokens. Finally I need the surface of that "detected" span of the named-entity which is recognized. At this point the offsets of the tokens might be helpful to simply take the sub-string from incoming text. 

I simply tried to use the returned offsets of the NER predictions to call the Decode method you mentioned. Unfortunately it sometimes throws an KeyNotFoundException as you already mentioned.

I currently switch back to BERTTokenizer which I forked and adjusted to return the offsets (in addition to fixing the infinite loop issue). I aso did some optimizations and reworks by using also memories and spans for tokenization on that implementation. 

If time permits I will have a deeper look on your new enumerator class, maybe that fits my needs better. I will maybe also give it a try to add offsets to your implementation by my own. I am with you that returning the string is not necessary but offsets are very helpful :)

**Comment by georg-jung** [comment]
I fixed #39 and published `0.5.18-alpha` on NuGet which contains the fix. Let me know if that works for you. I'll take a look at adding an offset output. It should be quite straight forward to add, probably [here](https://github.com/georg-jung/FastBertTokenizer/blob/744b92dd4d51a634122a9a3d34d3ad7f40ecb6d6/src/FastBertTokenizer/BertTokenizer.cs#L391). I need to think about the API though (and measure the perf impact, but I guess that it wont be large) because my goal is to keep it as easy to use as possible. Would be interesting to know what you found hard to grasp from a consumer's perspective if you mind sharing :).

**Comment by georg-jung** [comment]
Did you give the new version a try since? Does it work for you? Are you still interested in the offsets?

**Comment by georg-jung** [comment]
Closed for now, feel free to comment or open a new issue if you need this feature.
